//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace HabilInformatica.Relatorios.RPT {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsMovAcesso")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsMovAcesso : global::System.Data.DataSet {
        
        private DS_VW_MOV_ACESSODataTable tableDS_VW_MOV_ACESSO;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public dsMovAcesso() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected dsMovAcesso(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["DS_VW_MOV_ACESSO"] != null)) {
                    base.Tables.Add(new DS_VW_MOV_ACESSODataTable(ds.Tables["DS_VW_MOV_ACESSO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public DS_VW_MOV_ACESSODataTable DS_VW_MOV_ACESSO {
            get {
                return this.tableDS_VW_MOV_ACESSO;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsMovAcesso cln = ((dsMovAcesso)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["DS_VW_MOV_ACESSO"] != null)) {
                    base.Tables.Add(new DS_VW_MOV_ACESSODataTable(ds.Tables["DS_VW_MOV_ACESSO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableDS_VW_MOV_ACESSO = ((DS_VW_MOV_ACESSODataTable)(base.Tables["DS_VW_MOV_ACESSO"]));
            if ((initTable == true)) {
                if ((this.tableDS_VW_MOV_ACESSO != null)) {
                    this.tableDS_VW_MOV_ACESSO.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsMovAcesso";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsMovAcesso.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableDS_VW_MOV_ACESSO = new DS_VW_MOV_ACESSODataTable();
            base.Tables.Add(this.tableDS_VW_MOV_ACESSO);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializeDS_VW_MOV_ACESSO() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsMovAcesso ds = new dsMovAcesso();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void DS_VW_MOV_ACESSORowChangeEventHandler(object sender, DS_VW_MOV_ACESSORowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class DS_VW_MOV_ACESSODataTable : global::System.Data.TypedTableBase<DS_VW_MOV_ACESSORow> {
            
            private global::System.Data.DataColumn columnCD_MOV_ACESSO;
            
            private global::System.Data.DataColumn columnDT_HR_ENTRADA;
            
            private global::System.Data.DataColumn columnDT_HR_SAIDA;
            
            private global::System.Data.DataColumn columnCD_TIPO_ACESSO;
            
            private global::System.Data.DataColumn columnTX_DOCUMENTO;
            
            private global::System.Data.DataColumn columnCD_PESSOA;
            
            private global::System.Data.DataColumn columnCD_CONTATO;
            
            private global::System.Data.DataColumn columnCD_VEICULO;
            
            private global::System.Data.DataColumn columnTX_OBS;
            
            private global::System.Data.DataColumn columnDS_TIPO_ACESSO;
            
            private global::System.Data.DataColumn columnNM_PESSOA;
            
            private global::System.Data.DataColumn columnNM_CONTATO;
            
            private global::System.Data.DataColumn columnNR_INSCRICAO;
            
            private global::System.Data.DataColumn columnNR_IERG;
            
            private global::System.Data.DataColumn columnPLACA;
            
            private global::System.Data.DataColumn columnNM_VEICULO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_MOV_ACESSODataTable() {
                this.TableName = "DS_VW_MOV_ACESSO";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal DS_VW_MOV_ACESSODataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected DS_VW_MOV_ACESSODataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_MOV_ACESSOColumn {
                get {
                    return this.columnCD_MOV_ACESSO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DT_HR_ENTRADAColumn {
                get {
                    return this.columnDT_HR_ENTRADA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DT_HR_SAIDAColumn {
                get {
                    return this.columnDT_HR_SAIDA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_TIPO_ACESSOColumn {
                get {
                    return this.columnCD_TIPO_ACESSO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn TX_DOCUMENTOColumn {
                get {
                    return this.columnTX_DOCUMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_PESSOAColumn {
                get {
                    return this.columnCD_PESSOA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_CONTATOColumn {
                get {
                    return this.columnCD_CONTATO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_VEICULOColumn {
                get {
                    return this.columnCD_VEICULO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn TX_OBSColumn {
                get {
                    return this.columnTX_OBS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DS_TIPO_ACESSOColumn {
                get {
                    return this.columnDS_TIPO_ACESSO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn NM_PESSOAColumn {
                get {
                    return this.columnNM_PESSOA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn NM_CONTATOColumn {
                get {
                    return this.columnNM_CONTATO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn NR_INSCRICAOColumn {
                get {
                    return this.columnNR_INSCRICAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn NR_IERGColumn {
                get {
                    return this.columnNR_IERG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn PLACAColumn {
                get {
                    return this.columnPLACA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn NM_VEICULOColumn {
                get {
                    return this.columnNM_VEICULO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_MOV_ACESSORow this[int index] {
                get {
                    return ((DS_VW_MOV_ACESSORow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DS_VW_MOV_ACESSORowChangeEventHandler DS_VW_MOV_ACESSORowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DS_VW_MOV_ACESSORowChangeEventHandler DS_VW_MOV_ACESSORowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DS_VW_MOV_ACESSORowChangeEventHandler DS_VW_MOV_ACESSORowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DS_VW_MOV_ACESSORowChangeEventHandler DS_VW_MOV_ACESSORowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddDS_VW_MOV_ACESSORow(DS_VW_MOV_ACESSORow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_MOV_ACESSORow AddDS_VW_MOV_ACESSORow(
                        long CD_MOV_ACESSO, 
                        System.DateTime DT_HR_ENTRADA, 
                        System.DateTime DT_HR_SAIDA, 
                        int CD_TIPO_ACESSO, 
                        string TX_DOCUMENTO, 
                        long CD_PESSOA, 
                        int CD_CONTATO, 
                        long CD_VEICULO, 
                        string TX_OBS, 
                        string DS_TIPO_ACESSO, 
                        string NM_PESSOA, 
                        string NM_CONTATO, 
                        string NR_INSCRICAO, 
                        string NR_IERG, 
                        string PLACA, 
                        string NM_VEICULO) {
                DS_VW_MOV_ACESSORow rowDS_VW_MOV_ACESSORow = ((DS_VW_MOV_ACESSORow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        CD_MOV_ACESSO,
                        DT_HR_ENTRADA,
                        DT_HR_SAIDA,
                        CD_TIPO_ACESSO,
                        TX_DOCUMENTO,
                        CD_PESSOA,
                        CD_CONTATO,
                        CD_VEICULO,
                        TX_OBS,
                        DS_TIPO_ACESSO,
                        NM_PESSOA,
                        NM_CONTATO,
                        NR_INSCRICAO,
                        NR_IERG,
                        PLACA,
                        NM_VEICULO};
                rowDS_VW_MOV_ACESSORow.ItemArray = columnValuesArray;
                this.Rows.Add(rowDS_VW_MOV_ACESSORow);
                return rowDS_VW_MOV_ACESSORow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                DS_VW_MOV_ACESSODataTable cln = ((DS_VW_MOV_ACESSODataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new DS_VW_MOV_ACESSODataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnCD_MOV_ACESSO = base.Columns["CD_MOV_ACESSO"];
                this.columnDT_HR_ENTRADA = base.Columns["DT_HR_ENTRADA"];
                this.columnDT_HR_SAIDA = base.Columns["DT_HR_SAIDA"];
                this.columnCD_TIPO_ACESSO = base.Columns["CD_TIPO_ACESSO"];
                this.columnTX_DOCUMENTO = base.Columns["TX_DOCUMENTO"];
                this.columnCD_PESSOA = base.Columns["CD_PESSOA"];
                this.columnCD_CONTATO = base.Columns["CD_CONTATO"];
                this.columnCD_VEICULO = base.Columns["CD_VEICULO"];
                this.columnTX_OBS = base.Columns["TX_OBS"];
                this.columnDS_TIPO_ACESSO = base.Columns["DS_TIPO_ACESSO"];
                this.columnNM_PESSOA = base.Columns["NM_PESSOA"];
                this.columnNM_CONTATO = base.Columns["NM_CONTATO"];
                this.columnNR_INSCRICAO = base.Columns["NR_INSCRICAO"];
                this.columnNR_IERG = base.Columns["NR_IERG"];
                this.columnPLACA = base.Columns["PLACA"];
                this.columnNM_VEICULO = base.Columns["NM_VEICULO"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnCD_MOV_ACESSO = new global::System.Data.DataColumn("CD_MOV_ACESSO", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_MOV_ACESSO);
                this.columnDT_HR_ENTRADA = new global::System.Data.DataColumn("DT_HR_ENTRADA", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDT_HR_ENTRADA);
                this.columnDT_HR_SAIDA = new global::System.Data.DataColumn("DT_HR_SAIDA", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDT_HR_SAIDA);
                this.columnCD_TIPO_ACESSO = new global::System.Data.DataColumn("CD_TIPO_ACESSO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_TIPO_ACESSO);
                this.columnTX_DOCUMENTO = new global::System.Data.DataColumn("TX_DOCUMENTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTX_DOCUMENTO);
                this.columnCD_PESSOA = new global::System.Data.DataColumn("CD_PESSOA", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_PESSOA);
                this.columnCD_CONTATO = new global::System.Data.DataColumn("CD_CONTATO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_CONTATO);
                this.columnCD_VEICULO = new global::System.Data.DataColumn("CD_VEICULO", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_VEICULO);
                this.columnTX_OBS = new global::System.Data.DataColumn("TX_OBS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTX_OBS);
                this.columnDS_TIPO_ACESSO = new global::System.Data.DataColumn("DS_TIPO_ACESSO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_TIPO_ACESSO);
                this.columnNM_PESSOA = new global::System.Data.DataColumn("NM_PESSOA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNM_PESSOA);
                this.columnNM_CONTATO = new global::System.Data.DataColumn("NM_CONTATO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNM_CONTATO);
                this.columnNR_INSCRICAO = new global::System.Data.DataColumn("NR_INSCRICAO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNR_INSCRICAO);
                this.columnNR_IERG = new global::System.Data.DataColumn("NR_IERG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNR_IERG);
                this.columnPLACA = new global::System.Data.DataColumn("PLACA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPLACA);
                this.columnNM_VEICULO = new global::System.Data.DataColumn("NM_VEICULO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNM_VEICULO);
                this.columnDT_HR_SAIDA.Caption = "DataColumn1";
                this.columnCD_PESSOA.Caption = "DataColumn1";
                this.columnCD_CONTATO.Caption = "DataColumn1";
                this.columnCD_VEICULO.Caption = "DataColumn1";
                this.columnTX_OBS.Caption = "DataColumn1";
                this.columnDS_TIPO_ACESSO.Caption = "DataColumn1";
                this.columnNM_PESSOA.Caption = "DataColumn1";
                this.columnNM_CONTATO.Caption = "DataColumn1";
                this.columnNR_INSCRICAO.Caption = "DataColumn1";
                this.columnNR_IERG.Caption = "DataColumn1";
                this.columnPLACA.Caption = "DataColumn1";
                this.columnNM_VEICULO.Caption = "DataColumn1";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_MOV_ACESSORow NewDS_VW_MOV_ACESSORow() {
                return ((DS_VW_MOV_ACESSORow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new DS_VW_MOV_ACESSORow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(DS_VW_MOV_ACESSORow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.DS_VW_MOV_ACESSORowChanged != null)) {
                    this.DS_VW_MOV_ACESSORowChanged(this, new DS_VW_MOV_ACESSORowChangeEvent(((DS_VW_MOV_ACESSORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.DS_VW_MOV_ACESSORowChanging != null)) {
                    this.DS_VW_MOV_ACESSORowChanging(this, new DS_VW_MOV_ACESSORowChangeEvent(((DS_VW_MOV_ACESSORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.DS_VW_MOV_ACESSORowDeleted != null)) {
                    this.DS_VW_MOV_ACESSORowDeleted(this, new DS_VW_MOV_ACESSORowChangeEvent(((DS_VW_MOV_ACESSORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.DS_VW_MOV_ACESSORowDeleting != null)) {
                    this.DS_VW_MOV_ACESSORowDeleting(this, new DS_VW_MOV_ACESSORowChangeEvent(((DS_VW_MOV_ACESSORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemoveDS_VW_MOV_ACESSORow(DS_VW_MOV_ACESSORow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsMovAcesso ds = new dsMovAcesso();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "DS_VW_MOV_ACESSODataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class DS_VW_MOV_ACESSORow : global::System.Data.DataRow {
            
            private DS_VW_MOV_ACESSODataTable tableDS_VW_MOV_ACESSO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal DS_VW_MOV_ACESSORow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableDS_VW_MOV_ACESSO = ((DS_VW_MOV_ACESSODataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public long CD_MOV_ACESSO {
                get {
                    try {
                        return ((long)(this[this.tableDS_VW_MOV_ACESSO.CD_MOV_ACESSOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_MOV_ACESSO\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.CD_MOV_ACESSOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public System.DateTime DT_HR_ENTRADA {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableDS_VW_MOV_ACESSO.DT_HR_ENTRADAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DT_HR_ENTRADA\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.DT_HR_ENTRADAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public System.DateTime DT_HR_SAIDA {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableDS_VW_MOV_ACESSO.DT_HR_SAIDAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DT_HR_SAIDA\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.DT_HR_SAIDAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int CD_TIPO_ACESSO {
                get {
                    try {
                        return ((int)(this[this.tableDS_VW_MOV_ACESSO.CD_TIPO_ACESSOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_TIPO_ACESSO\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.CD_TIPO_ACESSOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string TX_DOCUMENTO {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_MOV_ACESSO.TX_DOCUMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'TX_DOCUMENTO\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.TX_DOCUMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public long CD_PESSOA {
                get {
                    try {
                        return ((long)(this[this.tableDS_VW_MOV_ACESSO.CD_PESSOAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_PESSOA\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.CD_PESSOAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int CD_CONTATO {
                get {
                    try {
                        return ((int)(this[this.tableDS_VW_MOV_ACESSO.CD_CONTATOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_CONTATO\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.CD_CONTATOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public long CD_VEICULO {
                get {
                    try {
                        return ((long)(this[this.tableDS_VW_MOV_ACESSO.CD_VEICULOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_VEICULO\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.CD_VEICULOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string TX_OBS {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_MOV_ACESSO.TX_OBSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'TX_OBS\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.TX_OBSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DS_TIPO_ACESSO {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_MOV_ACESSO.DS_TIPO_ACESSOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DS_TIPO_ACESSO\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.DS_TIPO_ACESSOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string NM_PESSOA {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_MOV_ACESSO.NM_PESSOAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'NM_PESSOA\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.NM_PESSOAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string NM_CONTATO {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_MOV_ACESSO.NM_CONTATOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'NM_CONTATO\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.NM_CONTATOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string NR_INSCRICAO {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_MOV_ACESSO.NR_INSCRICAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'NR_INSCRICAO\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.NR_INSCRICAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string NR_IERG {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_MOV_ACESSO.NR_IERGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'NR_IERG\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.NR_IERGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string PLACA {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_MOV_ACESSO.PLACAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'PLACA\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.PLACAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string NM_VEICULO {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_MOV_ACESSO.NM_VEICULOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'NM_VEICULO\' na tabela \'DS_VW_MOV_ACESSO\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_MOV_ACESSO.NM_VEICULOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_MOV_ACESSONull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.CD_MOV_ACESSOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_MOV_ACESSONull() {
                this[this.tableDS_VW_MOV_ACESSO.CD_MOV_ACESSOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDT_HR_ENTRADANull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.DT_HR_ENTRADAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDT_HR_ENTRADANull() {
                this[this.tableDS_VW_MOV_ACESSO.DT_HR_ENTRADAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDT_HR_SAIDANull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.DT_HR_SAIDAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDT_HR_SAIDANull() {
                this[this.tableDS_VW_MOV_ACESSO.DT_HR_SAIDAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_TIPO_ACESSONull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.CD_TIPO_ACESSOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_TIPO_ACESSONull() {
                this[this.tableDS_VW_MOV_ACESSO.CD_TIPO_ACESSOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsTX_DOCUMENTONull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.TX_DOCUMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetTX_DOCUMENTONull() {
                this[this.tableDS_VW_MOV_ACESSO.TX_DOCUMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_PESSOANull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.CD_PESSOAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_PESSOANull() {
                this[this.tableDS_VW_MOV_ACESSO.CD_PESSOAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_CONTATONull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.CD_CONTATOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_CONTATONull() {
                this[this.tableDS_VW_MOV_ACESSO.CD_CONTATOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_VEICULONull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.CD_VEICULOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_VEICULONull() {
                this[this.tableDS_VW_MOV_ACESSO.CD_VEICULOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsTX_OBSNull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.TX_OBSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetTX_OBSNull() {
                this[this.tableDS_VW_MOV_ACESSO.TX_OBSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDS_TIPO_ACESSONull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.DS_TIPO_ACESSOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDS_TIPO_ACESSONull() {
                this[this.tableDS_VW_MOV_ACESSO.DS_TIPO_ACESSOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsNM_PESSOANull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.NM_PESSOAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetNM_PESSOANull() {
                this[this.tableDS_VW_MOV_ACESSO.NM_PESSOAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsNM_CONTATONull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.NM_CONTATOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetNM_CONTATONull() {
                this[this.tableDS_VW_MOV_ACESSO.NM_CONTATOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsNR_INSCRICAONull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.NR_INSCRICAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetNR_INSCRICAONull() {
                this[this.tableDS_VW_MOV_ACESSO.NR_INSCRICAOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsNR_IERGNull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.NR_IERGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetNR_IERGNull() {
                this[this.tableDS_VW_MOV_ACESSO.NR_IERGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPLACANull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.PLACAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPLACANull() {
                this[this.tableDS_VW_MOV_ACESSO.PLACAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsNM_VEICULONull() {
                return this.IsNull(this.tableDS_VW_MOV_ACESSO.NM_VEICULOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetNM_VEICULONull() {
                this[this.tableDS_VW_MOV_ACESSO.NM_VEICULOColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class DS_VW_MOV_ACESSORowChangeEvent : global::System.EventArgs {
            
            private DS_VW_MOV_ACESSORow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_MOV_ACESSORowChangeEvent(DS_VW_MOV_ACESSORow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_MOV_ACESSORow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591