//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace HabilInformatica.Pages.Financeiros.RPT {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsCtaPagar")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsCtaPagar : global::System.Data.DataSet {
        
        private DS_VW_CTA_PAGARDataTable tableDS_VW_CTA_PAGAR;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public dsCtaPagar() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected dsCtaPagar(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["DS_VW_CTA_PAGAR"] != null)) {
                    base.Tables.Add(new DS_VW_CTA_PAGARDataTable(ds.Tables["DS_VW_CTA_PAGAR"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public DS_VW_CTA_PAGARDataTable DS_VW_CTA_PAGAR {
            get {
                return this.tableDS_VW_CTA_PAGAR;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsCtaPagar cln = ((dsCtaPagar)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["DS_VW_CTA_PAGAR"] != null)) {
                    base.Tables.Add(new DS_VW_CTA_PAGARDataTable(ds.Tables["DS_VW_CTA_PAGAR"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableDS_VW_CTA_PAGAR = ((DS_VW_CTA_PAGARDataTable)(base.Tables["DS_VW_CTA_PAGAR"]));
            if ((initTable == true)) {
                if ((this.tableDS_VW_CTA_PAGAR != null)) {
                    this.tableDS_VW_CTA_PAGAR.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsCtaPagar";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsMovAcesso.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableDS_VW_CTA_PAGAR = new DS_VW_CTA_PAGARDataTable();
            base.Tables.Add(this.tableDS_VW_CTA_PAGAR);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializeDS_VW_CTA_PAGAR() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsCtaPagar ds = new dsCtaPagar();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void DS_VW_CTA_PAGARRowChangeEventHandler(object sender, DS_VW_CTA_PAGARRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class DS_VW_CTA_PAGARDataTable : global::System.Data.TypedTableBase<DS_VW_CTA_PAGARRow> {
            
            private global::System.Data.DataColumn columnCD_DOCUMENTO;
            
            private global::System.Data.DataColumn columnDG_DOCUMENTO;
            
            private global::System.Data.DataColumn columnRAZ_SOCIAL;
            
            private global::System.Data.DataColumn columnDT_HR_ENTRADA;
            
            private global::System.Data.DataColumn columnDT_HR_EMISSAO;
            
            private global::System.Data.DataColumn columnDT_VENCIMENTO;
            
            private global::System.Data.DataColumn columnNR_SR_DOCUMENTO;
            
            private global::System.Data.DataColumn columnVL_TOTAL_DOCUMENTO;
            
            private global::System.Data.DataColumn columnVL_TOTAL_DESCONTO;
            
            private global::System.Data.DataColumn columnVL_TOTAL_ACRESCIMO;
            
            private global::System.Data.DataColumn columnVL_TOTAL_GERAL;
            
            private global::System.Data.DataColumn columnCD_SITUACAO;
            
            private global::System.Data.DataColumn columnDS_SITUACAO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_CTA_PAGARDataTable() {
                this.TableName = "DS_VW_CTA_PAGAR";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal DS_VW_CTA_PAGARDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected DS_VW_CTA_PAGARDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_DOCUMENTOColumn {
                get {
                    return this.columnCD_DOCUMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DG_DOCUMENTOColumn {
                get {
                    return this.columnDG_DOCUMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn RAZ_SOCIALColumn {
                get {
                    return this.columnRAZ_SOCIAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DT_HR_ENTRADAColumn {
                get {
                    return this.columnDT_HR_ENTRADA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DT_HR_EMISSAOColumn {
                get {
                    return this.columnDT_HR_EMISSAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DT_VENCIMENTOColumn {
                get {
                    return this.columnDT_VENCIMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn NR_SR_DOCUMENTOColumn {
                get {
                    return this.columnNR_SR_DOCUMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn VL_TOTAL_DOCUMENTOColumn {
                get {
                    return this.columnVL_TOTAL_DOCUMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn VL_TOTAL_DESCONTOColumn {
                get {
                    return this.columnVL_TOTAL_DESCONTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn VL_TOTAL_ACRESCIMOColumn {
                get {
                    return this.columnVL_TOTAL_ACRESCIMO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn VL_TOTAL_GERALColumn {
                get {
                    return this.columnVL_TOTAL_GERAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_SITUACAOColumn {
                get {
                    return this.columnCD_SITUACAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DS_SITUACAOColumn {
                get {
                    return this.columnDS_SITUACAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_CTA_PAGARRow this[int index] {
                get {
                    return ((DS_VW_CTA_PAGARRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DS_VW_CTA_PAGARRowChangeEventHandler DS_VW_CTA_PAGARRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DS_VW_CTA_PAGARRowChangeEventHandler DS_VW_CTA_PAGARRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DS_VW_CTA_PAGARRowChangeEventHandler DS_VW_CTA_PAGARRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DS_VW_CTA_PAGARRowChangeEventHandler DS_VW_CTA_PAGARRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddDS_VW_CTA_PAGARRow(DS_VW_CTA_PAGARRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_CTA_PAGARRow AddDS_VW_CTA_PAGARRow(decimal CD_DOCUMENTO, string DG_DOCUMENTO, string RAZ_SOCIAL, System.DateTime DT_HR_ENTRADA, System.DateTime DT_HR_EMISSAO, System.DateTime DT_VENCIMENTO, string NR_SR_DOCUMENTO, decimal VL_TOTAL_DOCUMENTO, double VL_TOTAL_DESCONTO, double VL_TOTAL_ACRESCIMO, double VL_TOTAL_GERAL, long CD_SITUACAO, string DS_SITUACAO) {
                DS_VW_CTA_PAGARRow rowDS_VW_CTA_PAGARRow = ((DS_VW_CTA_PAGARRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        CD_DOCUMENTO,
                        DG_DOCUMENTO,
                        RAZ_SOCIAL,
                        DT_HR_ENTRADA,
                        DT_HR_EMISSAO,
                        DT_VENCIMENTO,
                        NR_SR_DOCUMENTO,
                        VL_TOTAL_DOCUMENTO,
                        VL_TOTAL_DESCONTO,
                        VL_TOTAL_ACRESCIMO,
                        VL_TOTAL_GERAL,
                        CD_SITUACAO,
                        DS_SITUACAO};
                rowDS_VW_CTA_PAGARRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowDS_VW_CTA_PAGARRow);
                return rowDS_VW_CTA_PAGARRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                DS_VW_CTA_PAGARDataTable cln = ((DS_VW_CTA_PAGARDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new DS_VW_CTA_PAGARDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnCD_DOCUMENTO = base.Columns["CD_DOCUMENTO"];
                this.columnDG_DOCUMENTO = base.Columns["DG_DOCUMENTO"];
                this.columnRAZ_SOCIAL = base.Columns["RAZ_SOCIAL"];
                this.columnDT_HR_ENTRADA = base.Columns["DT_HR_ENTRADA"];
                this.columnDT_HR_EMISSAO = base.Columns["DT_HR_EMISSAO"];
                this.columnDT_VENCIMENTO = base.Columns["DT_VENCIMENTO"];
                this.columnNR_SR_DOCUMENTO = base.Columns["NR_SR_DOCUMENTO"];
                this.columnVL_TOTAL_DOCUMENTO = base.Columns["VL_TOTAL_DOCUMENTO"];
                this.columnVL_TOTAL_DESCONTO = base.Columns["VL_TOTAL_DESCONTO"];
                this.columnVL_TOTAL_ACRESCIMO = base.Columns["VL_TOTAL_ACRESCIMO"];
                this.columnVL_TOTAL_GERAL = base.Columns["VL_TOTAL_GERAL"];
                this.columnCD_SITUACAO = base.Columns["CD_SITUACAO"];
                this.columnDS_SITUACAO = base.Columns["DS_SITUACAO"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnCD_DOCUMENTO = new global::System.Data.DataColumn("CD_DOCUMENTO", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_DOCUMENTO);
                this.columnDG_DOCUMENTO = new global::System.Data.DataColumn("DG_DOCUMENTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDG_DOCUMENTO);
                this.columnRAZ_SOCIAL = new global::System.Data.DataColumn("RAZ_SOCIAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRAZ_SOCIAL);
                this.columnDT_HR_ENTRADA = new global::System.Data.DataColumn("DT_HR_ENTRADA", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDT_HR_ENTRADA);
                this.columnDT_HR_EMISSAO = new global::System.Data.DataColumn("DT_HR_EMISSAO", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDT_HR_EMISSAO);
                this.columnDT_VENCIMENTO = new global::System.Data.DataColumn("DT_VENCIMENTO", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDT_VENCIMENTO);
                this.columnNR_SR_DOCUMENTO = new global::System.Data.DataColumn("NR_SR_DOCUMENTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNR_SR_DOCUMENTO);
                this.columnVL_TOTAL_DOCUMENTO = new global::System.Data.DataColumn("VL_TOTAL_DOCUMENTO", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVL_TOTAL_DOCUMENTO);
                this.columnVL_TOTAL_DESCONTO = new global::System.Data.DataColumn("VL_TOTAL_DESCONTO", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVL_TOTAL_DESCONTO);
                this.columnVL_TOTAL_ACRESCIMO = new global::System.Data.DataColumn("VL_TOTAL_ACRESCIMO", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVL_TOTAL_ACRESCIMO);
                this.columnVL_TOTAL_GERAL = new global::System.Data.DataColumn("VL_TOTAL_GERAL", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVL_TOTAL_GERAL);
                this.columnCD_SITUACAO = new global::System.Data.DataColumn("CD_SITUACAO", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_SITUACAO);
                this.columnDS_SITUACAO = new global::System.Data.DataColumn("DS_SITUACAO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_SITUACAO);
                this.columnCD_DOCUMENTO.Caption = "DataColumn1";
                this.columnRAZ_SOCIAL.Caption = "DataColumn1";
                this.columnDT_VENCIMENTO.Caption = "DataColumn1";
                this.columnNR_SR_DOCUMENTO.Caption = "DataColumn1";
                this.columnVL_TOTAL_DOCUMENTO.Caption = "DataColumn1";
                this.columnVL_TOTAL_DESCONTO.Caption = "DataColumn1";
                this.columnVL_TOTAL_ACRESCIMO.Caption = "DataColumn1";
                this.columnVL_TOTAL_GERAL.Caption = "DataColumn1";
                this.columnCD_SITUACAO.Caption = "DataColumn1";
                this.columnDS_SITUACAO.Caption = "DataColumn1";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_CTA_PAGARRow NewDS_VW_CTA_PAGARRow() {
                return ((DS_VW_CTA_PAGARRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new DS_VW_CTA_PAGARRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(DS_VW_CTA_PAGARRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.DS_VW_CTA_PAGARRowChanged != null)) {
                    this.DS_VW_CTA_PAGARRowChanged(this, new DS_VW_CTA_PAGARRowChangeEvent(((DS_VW_CTA_PAGARRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.DS_VW_CTA_PAGARRowChanging != null)) {
                    this.DS_VW_CTA_PAGARRowChanging(this, new DS_VW_CTA_PAGARRowChangeEvent(((DS_VW_CTA_PAGARRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.DS_VW_CTA_PAGARRowDeleted != null)) {
                    this.DS_VW_CTA_PAGARRowDeleted(this, new DS_VW_CTA_PAGARRowChangeEvent(((DS_VW_CTA_PAGARRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.DS_VW_CTA_PAGARRowDeleting != null)) {
                    this.DS_VW_CTA_PAGARRowDeleting(this, new DS_VW_CTA_PAGARRowChangeEvent(((DS_VW_CTA_PAGARRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemoveDS_VW_CTA_PAGARRow(DS_VW_CTA_PAGARRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsCtaPagar ds = new dsCtaPagar();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "DS_VW_CTA_PAGARDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class DS_VW_CTA_PAGARRow : global::System.Data.DataRow {
            
            private DS_VW_CTA_PAGARDataTable tableDS_VW_CTA_PAGAR;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal DS_VW_CTA_PAGARRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableDS_VW_CTA_PAGAR = ((DS_VW_CTA_PAGARDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public decimal CD_DOCUMENTO {
                get {
                    try {
                        return ((decimal)(this[this.tableDS_VW_CTA_PAGAR.CD_DOCUMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_DOCUMENTO\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.CD_DOCUMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DG_DOCUMENTO {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_CTA_PAGAR.DG_DOCUMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DG_DOCUMENTO\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.DG_DOCUMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string RAZ_SOCIAL {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_CTA_PAGAR.RAZ_SOCIALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'RAZ_SOCIAL\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.RAZ_SOCIALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public System.DateTime DT_HR_ENTRADA {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableDS_VW_CTA_PAGAR.DT_HR_ENTRADAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DT_HR_ENTRADA\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.DT_HR_ENTRADAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public System.DateTime DT_HR_EMISSAO {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableDS_VW_CTA_PAGAR.DT_HR_EMISSAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DT_HR_EMISSAO\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.DT_HR_EMISSAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public System.DateTime DT_VENCIMENTO {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableDS_VW_CTA_PAGAR.DT_VENCIMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DT_VENCIMENTO\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.DT_VENCIMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string NR_SR_DOCUMENTO {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_CTA_PAGAR.NR_SR_DOCUMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'NR_SR_DOCUMENTO\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.NR_SR_DOCUMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public decimal VL_TOTAL_DOCUMENTO {
                get {
                    try {
                        return ((decimal)(this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_DOCUMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'VL_TOTAL_DOCUMENTO\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_DOCUMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double VL_TOTAL_DESCONTO {
                get {
                    try {
                        return ((double)(this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_DESCONTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'VL_TOTAL_DESCONTO\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_DESCONTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double VL_TOTAL_ACRESCIMO {
                get {
                    try {
                        return ((double)(this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_ACRESCIMOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'VL_TOTAL_ACRESCIMO\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_ACRESCIMOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double VL_TOTAL_GERAL {
                get {
                    try {
                        return ((double)(this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_GERALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'VL_TOTAL_GERAL\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_GERALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public long CD_SITUACAO {
                get {
                    try {
                        return ((long)(this[this.tableDS_VW_CTA_PAGAR.CD_SITUACAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_SITUACAO\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.CD_SITUACAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DS_SITUACAO {
                get {
                    try {
                        return ((string)(this[this.tableDS_VW_CTA_PAGAR.DS_SITUACAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DS_SITUACAO\' na tabela \'DS_VW_CTA_PAGAR\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableDS_VW_CTA_PAGAR.DS_SITUACAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_DOCUMENTONull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.CD_DOCUMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_DOCUMENTONull() {
                this[this.tableDS_VW_CTA_PAGAR.CD_DOCUMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDG_DOCUMENTONull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.DG_DOCUMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDG_DOCUMENTONull() {
                this[this.tableDS_VW_CTA_PAGAR.DG_DOCUMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsRAZ_SOCIALNull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.RAZ_SOCIALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetRAZ_SOCIALNull() {
                this[this.tableDS_VW_CTA_PAGAR.RAZ_SOCIALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDT_HR_ENTRADANull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.DT_HR_ENTRADAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDT_HR_ENTRADANull() {
                this[this.tableDS_VW_CTA_PAGAR.DT_HR_ENTRADAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDT_HR_EMISSAONull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.DT_HR_EMISSAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDT_HR_EMISSAONull() {
                this[this.tableDS_VW_CTA_PAGAR.DT_HR_EMISSAOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDT_VENCIMENTONull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.DT_VENCIMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDT_VENCIMENTONull() {
                this[this.tableDS_VW_CTA_PAGAR.DT_VENCIMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsNR_SR_DOCUMENTONull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.NR_SR_DOCUMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetNR_SR_DOCUMENTONull() {
                this[this.tableDS_VW_CTA_PAGAR.NR_SR_DOCUMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsVL_TOTAL_DOCUMENTONull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.VL_TOTAL_DOCUMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetVL_TOTAL_DOCUMENTONull() {
                this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_DOCUMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsVL_TOTAL_DESCONTONull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.VL_TOTAL_DESCONTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetVL_TOTAL_DESCONTONull() {
                this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_DESCONTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsVL_TOTAL_ACRESCIMONull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.VL_TOTAL_ACRESCIMOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetVL_TOTAL_ACRESCIMONull() {
                this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_ACRESCIMOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsVL_TOTAL_GERALNull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.VL_TOTAL_GERALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetVL_TOTAL_GERALNull() {
                this[this.tableDS_VW_CTA_PAGAR.VL_TOTAL_GERALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_SITUACAONull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.CD_SITUACAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_SITUACAONull() {
                this[this.tableDS_VW_CTA_PAGAR.CD_SITUACAOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDS_SITUACAONull() {
                return this.IsNull(this.tableDS_VW_CTA_PAGAR.DS_SITUACAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDS_SITUACAONull() {
                this[this.tableDS_VW_CTA_PAGAR.DS_SITUACAOColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class DS_VW_CTA_PAGARRowChangeEvent : global::System.EventArgs {
            
            private DS_VW_CTA_PAGARRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_CTA_PAGARRowChangeEvent(DS_VW_CTA_PAGARRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DS_VW_CTA_PAGARRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591