
/****** Object:  View [dbo].[VW_LIS_DOCUMENTO]    Script Date: 17/09/2020 16:21:53 ******/
DROP VIEW [dbo].[VW_LIS_DOCUMENTO]
GO

/****** Object:  View [dbo].[VW_LIS_DOCUMENTO]    Script Date: 17/09/2020 16:21:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_LIS_DOCUMENTO]
AS
SELECT        doc.NR_DOCUMENTO, doc.CD_DOCUMENTO, ISNULL(doc.CD_SEPARACAO, 0) AS CD_SEPARACAO, doc.CD_TIPO_DOCUMENTO, doc.CD_EMPRESA, doc.CD_SITUACAO, doc.DT_HR_EMISSAO, 
                         doc.CD_VENDEDOR, ISNULL(doc.CD_DOCA, 0) AS CD_DOCA_DOCUMENTO, pd.CD_PESSOA AS CD_CLIENTE, pd.CD_BAIRRO, pd.DS_BAIRRO, pd.RAZ_SOCIAL AS NM_CLIENTE, pd.NR_ENDERECO, 
                         pd.COMPLEMENTO, pd.LOGRADOURO, pd.CD_CEP, pd.TELEFONE_1, MC.DS_MUNICIPIO, p.CD_TRANSPORTADOR, HT.DS_TIPO AS DS_SITUACAO, d.DS_DOCA AS DS_DOCA_DOCUMENTO, 
                         PV.NM_PESSOA AS NM_VENDEDOR, PV.CD_PESSOA, ISNULL(p.CD_DOCA, 0) AS CD_DOCA_CLIENTE, PST.RAZ_SOCIAL AS NM_TRANSPORTE, COUNT(PDD.CD_PROD_DOCUMENTO) AS QT_PROD_COUNT
FROM            dbo.DOCUMENTO AS doc INNER JOIN
                         dbo.PESSOA_DO_DOCUMENTO AS pd ON doc.CD_DOCUMENTO = pd.CD_DOCUMENTO AND pd.TP_PESSOA = 12 INNER JOIN
                         dbo.PESSOA AS p ON pd.CD_PESSOA = p.CD_PESSOA INNER JOIN
                         dbo.MUNICIPIO AS MC ON MC.CD_MUNICIPIO = pd.CD_MUNICIPIO INNER JOIN
                         dbo.HABIL_TIPO AS HT ON HT.CD_TIPO = doc.CD_SITUACAO INNER JOIN
                         dbo.DOCA AS d ON d.CD_DOCA = p.CD_DOCA AND d.CD_EMPRESA = doc.CD_EMPRESA INNER JOIN
                         dbo.PRODUTO_DO_DOCUMENTO AS PDD ON doc.CD_DOCUMENTO = PDD.CD_DOCUMENTO INNER JOIN
                         dbo.VENDEDOR AS V ON V.CD_VENDEDOR = doc.CD_VENDEDOR INNER JOIN
                         dbo.PESSOA AS PV ON PV.CD_PESSOA = V.CD_PESSOA INNER JOIN
                         dbo.PESSOA_DO_DOCUMENTO AS PST ON doc.CD_DOCUMENTO = PST.CD_DOCUMENTO AND PST.TP_PESSOA = 13
GROUP BY doc.NR_DOCUMENTO, doc.CD_DOCUMENTO, doc.CD_SEPARACAO, doc.CD_TIPO_DOCUMENTO, doc.CD_EMPRESA, doc.CD_SITUACAO, doc.DT_HR_EMISSAO, doc.CD_VENDEDOR, ISNULL(doc.CD_DOCA, 0), 
                         pd.CD_PESSOA, pd.CD_BAIRRO, pd.DS_BAIRRO, pd.RAZ_SOCIAL, pd.NR_ENDERECO, pd.COMPLEMENTO, pd.LOGRADOURO, pd.CD_CEP, MC.DS_MUNICIPIO, pd.TELEFONE_1, p.CD_TRANSPORTADOR, 
                         d.DS_DOCA, PV.NM_PESSOA, PV.CD_PESSOA, ISNULL(p.CD_DOCA, 0), PST.RAZ_SOCIAL, HT.DS_TIPO

GO
