//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace HabilInformatica.Pages.Impostos.RPT {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsRegFisIPI")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsRegFisIPI : global::System.Data.DataSet {
        
        private REGRA_FISCAL_IPIDataTable tableREGRA_FISCAL_IPI;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public dsRegFisIPI() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected dsRegFisIPI(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["REGRA_FISCAL_IPI"] != null)) {
                    base.Tables.Add(new REGRA_FISCAL_IPIDataTable(ds.Tables["REGRA_FISCAL_IPI"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public REGRA_FISCAL_IPIDataTable REGRA_FISCAL_IPI {
            get {
                return this.tableREGRA_FISCAL_IPI;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsRegFisIPI cln = ((dsRegFisIPI)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["REGRA_FISCAL_IPI"] != null)) {
                    base.Tables.Add(new REGRA_FISCAL_IPIDataTable(ds.Tables["REGRA_FISCAL_IPI"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableREGRA_FISCAL_IPI = ((REGRA_FISCAL_IPIDataTable)(base.Tables["REGRA_FISCAL_IPI"]));
            if ((initTable == true)) {
                if ((this.tableREGRA_FISCAL_IPI != null)) {
                    this.tableREGRA_FISCAL_IPI.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsRegFisIPI";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsRegFisIPI.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableREGRA_FISCAL_IPI = new REGRA_FISCAL_IPIDataTable();
            base.Tables.Add(this.tableREGRA_FISCAL_IPI);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializeREGRA_FISCAL_IPI() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsRegFisIPI ds = new dsRegFisIPI();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void REGRA_FISCAL_IPIRowChangeEventHandler(object sender, REGRA_FISCAL_IPIRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class REGRA_FISCAL_IPIDataTable : global::System.Data.TypedTableBase<REGRA_FISCAL_IPIRow> {
            
            private global::System.Data.DataColumn columnCD_REGRA_FISCAL_IPI;
            
            private global::System.Data.DataColumn columnCD_NCM;
            
            private global::System.Data.DataColumn columnDS_NCM;
            
            private global::System.Data.DataColumn columnCD_SITUACAO;
            
            private global::System.Data.DataColumn columnCD_TIPO;
            
            private global::System.Data.DataColumn columnVL_PCT_IPI;
            
            private global::System.Data.DataColumn columnCD_ENQUADRAMENTO;
            
            private global::System.Data.DataColumn columnDT_ATUALIZACAO;
            
            private global::System.Data.DataColumn columnDT_VIGENCIA;
            
            private global::System.Data.DataColumn columnCD_EX;
            
            private global::System.Data.DataColumn columnDS_TIPO_TRIBUTACAO;
            
            private global::System.Data.DataColumn columnDS_TIPO_SITUACAO;
            
            private global::System.Data.DataColumn columnCD_CST_IPI;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public REGRA_FISCAL_IPIDataTable() {
                this.TableName = "REGRA_FISCAL_IPI";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal REGRA_FISCAL_IPIDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected REGRA_FISCAL_IPIDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_REGRA_FISCAL_IPIColumn {
                get {
                    return this.columnCD_REGRA_FISCAL_IPI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_NCMColumn {
                get {
                    return this.columnCD_NCM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DS_NCMColumn {
                get {
                    return this.columnDS_NCM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_SITUACAOColumn {
                get {
                    return this.columnCD_SITUACAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_TIPOColumn {
                get {
                    return this.columnCD_TIPO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn VL_PCT_IPIColumn {
                get {
                    return this.columnVL_PCT_IPI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_ENQUADRAMENTOColumn {
                get {
                    return this.columnCD_ENQUADRAMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DT_ATUALIZACAOColumn {
                get {
                    return this.columnDT_ATUALIZACAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DT_VIGENCIAColumn {
                get {
                    return this.columnDT_VIGENCIA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_EXColumn {
                get {
                    return this.columnCD_EX;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DS_TIPO_TRIBUTACAOColumn {
                get {
                    return this.columnDS_TIPO_TRIBUTACAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DS_TIPO_SITUACAOColumn {
                get {
                    return this.columnDS_TIPO_SITUACAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CD_CST_IPIColumn {
                get {
                    return this.columnCD_CST_IPI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public REGRA_FISCAL_IPIRow this[int index] {
                get {
                    return ((REGRA_FISCAL_IPIRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event REGRA_FISCAL_IPIRowChangeEventHandler REGRA_FISCAL_IPIRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event REGRA_FISCAL_IPIRowChangeEventHandler REGRA_FISCAL_IPIRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event REGRA_FISCAL_IPIRowChangeEventHandler REGRA_FISCAL_IPIRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event REGRA_FISCAL_IPIRowChangeEventHandler REGRA_FISCAL_IPIRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddREGRA_FISCAL_IPIRow(REGRA_FISCAL_IPIRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public REGRA_FISCAL_IPIRow AddREGRA_FISCAL_IPIRow(decimal CD_REGRA_FISCAL_IPI, string CD_NCM, string DS_NCM, int CD_SITUACAO, int CD_TIPO, decimal VL_PCT_IPI, short CD_ENQUADRAMENTO, System.DateTime DT_ATUALIZACAO, System.DateTime DT_VIGENCIA, string CD_EX, string DS_TIPO_TRIBUTACAO, string DS_TIPO_SITUACAO, short CD_CST_IPI) {
                REGRA_FISCAL_IPIRow rowREGRA_FISCAL_IPIRow = ((REGRA_FISCAL_IPIRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        CD_REGRA_FISCAL_IPI,
                        CD_NCM,
                        DS_NCM,
                        CD_SITUACAO,
                        CD_TIPO,
                        VL_PCT_IPI,
                        CD_ENQUADRAMENTO,
                        DT_ATUALIZACAO,
                        DT_VIGENCIA,
                        CD_EX,
                        DS_TIPO_TRIBUTACAO,
                        DS_TIPO_SITUACAO,
                        CD_CST_IPI};
                rowREGRA_FISCAL_IPIRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowREGRA_FISCAL_IPIRow);
                return rowREGRA_FISCAL_IPIRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                REGRA_FISCAL_IPIDataTable cln = ((REGRA_FISCAL_IPIDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new REGRA_FISCAL_IPIDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnCD_REGRA_FISCAL_IPI = base.Columns["CD_REGRA_FISCAL_IPI"];
                this.columnCD_NCM = base.Columns["CD_NCM"];
                this.columnDS_NCM = base.Columns["DS_NCM"];
                this.columnCD_SITUACAO = base.Columns["CD_SITUACAO"];
                this.columnCD_TIPO = base.Columns["CD_TIPO"];
                this.columnVL_PCT_IPI = base.Columns["VL_PCT_IPI"];
                this.columnCD_ENQUADRAMENTO = base.Columns["CD_ENQUADRAMENTO"];
                this.columnDT_ATUALIZACAO = base.Columns["DT_ATUALIZACAO"];
                this.columnDT_VIGENCIA = base.Columns["DT_VIGENCIA"];
                this.columnCD_EX = base.Columns["CD_EX"];
                this.columnDS_TIPO_TRIBUTACAO = base.Columns["DS_TIPO_TRIBUTACAO"];
                this.columnDS_TIPO_SITUACAO = base.Columns["DS_TIPO_SITUACAO"];
                this.columnCD_CST_IPI = base.Columns["CD_CST_IPI"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnCD_REGRA_FISCAL_IPI = new global::System.Data.DataColumn("CD_REGRA_FISCAL_IPI", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_REGRA_FISCAL_IPI);
                this.columnCD_NCM = new global::System.Data.DataColumn("CD_NCM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_NCM);
                this.columnDS_NCM = new global::System.Data.DataColumn("DS_NCM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_NCM);
                this.columnCD_SITUACAO = new global::System.Data.DataColumn("CD_SITUACAO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_SITUACAO);
                this.columnCD_TIPO = new global::System.Data.DataColumn("CD_TIPO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_TIPO);
                this.columnVL_PCT_IPI = new global::System.Data.DataColumn("VL_PCT_IPI", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVL_PCT_IPI);
                this.columnCD_ENQUADRAMENTO = new global::System.Data.DataColumn("CD_ENQUADRAMENTO", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_ENQUADRAMENTO);
                this.columnDT_ATUALIZACAO = new global::System.Data.DataColumn("DT_ATUALIZACAO", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDT_ATUALIZACAO);
                this.columnDT_VIGENCIA = new global::System.Data.DataColumn("DT_VIGENCIA", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDT_VIGENCIA);
                this.columnCD_EX = new global::System.Data.DataColumn("CD_EX", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_EX);
                this.columnDS_TIPO_TRIBUTACAO = new global::System.Data.DataColumn("DS_TIPO_TRIBUTACAO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_TIPO_TRIBUTACAO);
                this.columnDS_TIPO_SITUACAO = new global::System.Data.DataColumn("DS_TIPO_SITUACAO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_TIPO_SITUACAO);
                this.columnCD_CST_IPI = new global::System.Data.DataColumn("CD_CST_IPI", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCD_CST_IPI);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public REGRA_FISCAL_IPIRow NewREGRA_FISCAL_IPIRow() {
                return ((REGRA_FISCAL_IPIRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new REGRA_FISCAL_IPIRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(REGRA_FISCAL_IPIRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.REGRA_FISCAL_IPIRowChanged != null)) {
                    this.REGRA_FISCAL_IPIRowChanged(this, new REGRA_FISCAL_IPIRowChangeEvent(((REGRA_FISCAL_IPIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.REGRA_FISCAL_IPIRowChanging != null)) {
                    this.REGRA_FISCAL_IPIRowChanging(this, new REGRA_FISCAL_IPIRowChangeEvent(((REGRA_FISCAL_IPIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.REGRA_FISCAL_IPIRowDeleted != null)) {
                    this.REGRA_FISCAL_IPIRowDeleted(this, new REGRA_FISCAL_IPIRowChangeEvent(((REGRA_FISCAL_IPIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.REGRA_FISCAL_IPIRowDeleting != null)) {
                    this.REGRA_FISCAL_IPIRowDeleting(this, new REGRA_FISCAL_IPIRowChangeEvent(((REGRA_FISCAL_IPIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemoveREGRA_FISCAL_IPIRow(REGRA_FISCAL_IPIRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsRegFisIPI ds = new dsRegFisIPI();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "REGRA_FISCAL_IPIDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class REGRA_FISCAL_IPIRow : global::System.Data.DataRow {
            
            private REGRA_FISCAL_IPIDataTable tableREGRA_FISCAL_IPI;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal REGRA_FISCAL_IPIRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableREGRA_FISCAL_IPI = ((REGRA_FISCAL_IPIDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public decimal CD_REGRA_FISCAL_IPI {
                get {
                    try {
                        return ((decimal)(this[this.tableREGRA_FISCAL_IPI.CD_REGRA_FISCAL_IPIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_REGRA_FISCAL_IPI\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.CD_REGRA_FISCAL_IPIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CD_NCM {
                get {
                    try {
                        return ((string)(this[this.tableREGRA_FISCAL_IPI.CD_NCMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_NCM\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.CD_NCMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DS_NCM {
                get {
                    try {
                        return ((string)(this[this.tableREGRA_FISCAL_IPI.DS_NCMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DS_NCM\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.DS_NCMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int CD_SITUACAO {
                get {
                    try {
                        return ((int)(this[this.tableREGRA_FISCAL_IPI.CD_SITUACAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_SITUACAO\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.CD_SITUACAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int CD_TIPO {
                get {
                    try {
                        return ((int)(this[this.tableREGRA_FISCAL_IPI.CD_TIPOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_TIPO\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.CD_TIPOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public decimal VL_PCT_IPI {
                get {
                    try {
                        return ((decimal)(this[this.tableREGRA_FISCAL_IPI.VL_PCT_IPIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'VL_PCT_IPI\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.VL_PCT_IPIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public short CD_ENQUADRAMENTO {
                get {
                    try {
                        return ((short)(this[this.tableREGRA_FISCAL_IPI.CD_ENQUADRAMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_ENQUADRAMENTO\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.CD_ENQUADRAMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public System.DateTime DT_ATUALIZACAO {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableREGRA_FISCAL_IPI.DT_ATUALIZACAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DT_ATUALIZACAO\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.DT_ATUALIZACAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public System.DateTime DT_VIGENCIA {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableREGRA_FISCAL_IPI.DT_VIGENCIAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DT_VIGENCIA\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.DT_VIGENCIAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CD_EX {
                get {
                    try {
                        return ((string)(this[this.tableREGRA_FISCAL_IPI.CD_EXColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_EX\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.CD_EXColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DS_TIPO_TRIBUTACAO {
                get {
                    try {
                        return ((string)(this[this.tableREGRA_FISCAL_IPI.DS_TIPO_TRIBUTACAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DS_TIPO_TRIBUTACAO\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.DS_TIPO_TRIBUTACAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DS_TIPO_SITUACAO {
                get {
                    try {
                        return ((string)(this[this.tableREGRA_FISCAL_IPI.DS_TIPO_SITUACAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'DS_TIPO_SITUACAO\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.DS_TIPO_SITUACAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public short CD_CST_IPI {
                get {
                    try {
                        return ((short)(this[this.tableREGRA_FISCAL_IPI.CD_CST_IPIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("O valor da coluna \'CD_CST_IPI\' na tabela \'REGRA_FISCAL_IPI\' é DBNull.", e);
                    }
                }
                set {
                    this[this.tableREGRA_FISCAL_IPI.CD_CST_IPIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_REGRA_FISCAL_IPINull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.CD_REGRA_FISCAL_IPIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_REGRA_FISCAL_IPINull() {
                this[this.tableREGRA_FISCAL_IPI.CD_REGRA_FISCAL_IPIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_NCMNull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.CD_NCMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_NCMNull() {
                this[this.tableREGRA_FISCAL_IPI.CD_NCMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDS_NCMNull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.DS_NCMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDS_NCMNull() {
                this[this.tableREGRA_FISCAL_IPI.DS_NCMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_SITUACAONull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.CD_SITUACAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_SITUACAONull() {
                this[this.tableREGRA_FISCAL_IPI.CD_SITUACAOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_TIPONull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.CD_TIPOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_TIPONull() {
                this[this.tableREGRA_FISCAL_IPI.CD_TIPOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsVL_PCT_IPINull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.VL_PCT_IPIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetVL_PCT_IPINull() {
                this[this.tableREGRA_FISCAL_IPI.VL_PCT_IPIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_ENQUADRAMENTONull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.CD_ENQUADRAMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_ENQUADRAMENTONull() {
                this[this.tableREGRA_FISCAL_IPI.CD_ENQUADRAMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDT_ATUALIZACAONull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.DT_ATUALIZACAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDT_ATUALIZACAONull() {
                this[this.tableREGRA_FISCAL_IPI.DT_ATUALIZACAOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDT_VIGENCIANull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.DT_VIGENCIAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDT_VIGENCIANull() {
                this[this.tableREGRA_FISCAL_IPI.DT_VIGENCIAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_EXNull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.CD_EXColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_EXNull() {
                this[this.tableREGRA_FISCAL_IPI.CD_EXColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDS_TIPO_TRIBUTACAONull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.DS_TIPO_TRIBUTACAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDS_TIPO_TRIBUTACAONull() {
                this[this.tableREGRA_FISCAL_IPI.DS_TIPO_TRIBUTACAOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDS_TIPO_SITUACAONull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.DS_TIPO_SITUACAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDS_TIPO_SITUACAONull() {
                this[this.tableREGRA_FISCAL_IPI.DS_TIPO_SITUACAOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCD_CST_IPINull() {
                return this.IsNull(this.tableREGRA_FISCAL_IPI.CD_CST_IPIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCD_CST_IPINull() {
                this[this.tableREGRA_FISCAL_IPI.CD_CST_IPIColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class REGRA_FISCAL_IPIRowChangeEvent : global::System.EventArgs {
            
            private REGRA_FISCAL_IPIRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public REGRA_FISCAL_IPIRowChangeEvent(REGRA_FISCAL_IPIRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public REGRA_FISCAL_IPIRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591